// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleOverview.Data;

#nullable disable

namespace PeopleOverview.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20230527182204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("PeopleOverview.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryOfResidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossAnnualSalary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSatisfiedWithSalary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSatisfiedWithWork")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surnames")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
